-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnlJCYgimYgQ0Qp2c
YwUvXjrBtlgJhVgsBBpx7Xm9dAegCgYIKoZIzj0DAQehRANCAAS8ycdxPcqsQNF6
OD10CcxidVLMGmKhimNs7/81gcR42otAW7senX4kRRUDkG+DrVPhrv2SxmF3yNN9
X6urZlSS
-----END PRIVATE KEY-----