# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mango Farm Bin Picking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mango Farm Bin Picking

pod 'GoogleSignIn'
pod 'MBProgressHUD', '~> 1.2.0'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Auth'
pod 'lottie-ios'
pod 'CalendarDateRangePickerViewController'
pod 'IQKeyboardManagerSwift'

end


post_install do |installer|
  installer.pods_project.targets.each do |t|
   t.build_configurations.each do |config|

    # to make @IBDesignable work with IB
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
    config.build_settings['CONFIGURATION_BUILD_DIR'] ='$PODS_CONFIGURATION_BUILD_DIR'
   end
 end
end
