-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgl5CJ6uopRVquI+Rl
f8afIe9BUZWwj/FskSsT27kA9RCgCgYIKoZIzj0DAQehRANCAAQZrcd9EKHUAS4O
RY4iUHoUFm2wSRiBhOYcZtZE3uVS5LZ/gPAiqutL8UbicVCp6eGpAx9XxcHyU9n7
/ypA+oS2
-----END PRIVATE KEY-----