# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KaiBall Athletics' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KaiBall Athletics
   
   pod 'Firebase/Firestore'
  
   pod 'Firebase/Crashlytics'

   pod 'Firebase/Analytics'
   
   pod 'Firebase/Storage'
   
   pod 'Firebase/Messaging'
   
   pod 'Firebase/Auth'

   pod 'FirebaseFirestoreSwift'

   pod 'MBProgressHUD', '~> 1.2.0'
   
   pod 'SDWebImage', '~> 4.0'

   pod 'CropViewController'
   
   pod 'IQKeyboardManagerSwift'


end
